
const data = [
    {
      id: 'NaNNA463undefined',
      name: 'Andy Parker',
      age: 21,
      image: 'https://andyparker.co/wp-content/uploads/2019/06/cropped-Profile-Picture-1.jpeg',
      email: 'andy.parker@example.com',
    },
    {
      id: '294562198',
      name: 'Mihailo Jović',
      age: 47,
      image: 'https://xsgames.co/randomusers/assets/avatars/male/62.jpg',
      email: 'mihailo.jovic@example.com',
    },
    {
      id: 'NaNNA281undefined',
      name: 'Ivan Petrov',
      age: 57,
      image: 'https://xsgames.co/randomusers/assets/avatars/male/63.jpg',
      email: 'ivan.petrov@example.com',
    },
    {
      id: 'ES 75 36 40 Q',
      name: 'Jenny Medina',
      age: 27,
      image: 'https://assets-global.website-files.com/645e162dc1579a2e016248dc/651fd8fe455f099d4666eb4f_4ha0mm9mavh0khcq6wn2hm2utib3.jpg',
      email: 'jenny.medina@example.com',
    },
    {
      id: 'BT 32 99 37 P',
      name: 'Talya Hoffman',
      age: 40,
      image: 'https://assets-global.website-files.com/645e162dc1579a2e016248dc/651bede96f6e865b2f579129_46opoibxnp3r9hjty85snvpx63x6.jpg',
      email: 'talya.hoffman@example.com',
    },
    {
      id: 'BB 58 36 13 U',
      name: 'John Doe',
      age: 43,
      image: 'https://xsgames.co/randomusers/assets/avatars/male/31.jpg',
      email: 'john.doe@example.com',
    },
    {
      id: '059737189',
      name: 'William Claire',
      age: 52,
      image: 'https://img.freepik.com/free-photo/smiling-man_1098-15443.jpg',
      email: 'william.claire@example.com',
    },
    {
      id: '2920214291853 13',
      name: 'Diane Martinez',
      age: 30,
      image: 'https://randomuser.me/api/portraits/women/51.jpg',
      email: 'diane.martinez@example.com',
    },
    {
      id: 'Elif',
      name: 'Elif Tokatlıoğlu',
      age: 36,
      image: 'https://img.freepik.com/free-photo/front-view-smiley-woman-with-earbuds_23-2148613052.jpg',
      email: 'elif.tokatlioglu@example.com',
    },
    {
      id: 'EA 05 60 05 K',
      name: 'Heather Byrd',
      age: 57,
      image: 'https://i.pinimg.com/564x/a2/de/39/a2de3954697c636276192afea0a6f661.jpg',
      email: 'heather.byrd@example.com',
    },
    {
      id: '219342235',
      name: 'Maya Williams',
      age: 29,
      image: 'https://www.userbrain.com/static/inviteYourOwnHeader1-878b5db230ca8e78e1451814ba07a834.jpg',
      email: 'maya.williams@example.com',
    },
    {
      id: 'NaNNA549undefined',
      name: 'Luukas Manni',
      age: 34,
      image: 'https://randomuser.me/api/portraits/men/40.jpg',
      email: 'luukas.manni@example.com',
    },
    {
      id: '75773788',
      name: 'Anya Karssen',
      age: 52,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0oNqnXQP4-i-snZY1Lz2ETNq1AfGDeTHlw6DeRWw8I6OKk-7U4GRUeV0RmkVr9N8M2_s&usqp=CAU',
      email: 'anya.karssen@example.com',
    },
    {
      id: '786-60-5441',
      name: 'Jenifer Reid',
      age: 22,
      image: 'https://elsasshall.com/wp-content/uploads/2021/10/holly.jpg',
      email: 'jenifer.reid@example.com',
    },
    {
      id: '2574875T',
      name: 'Jacob Neal',
      age: 57,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcYdkxG4MYgDR4u4Qr6kjKUtxNuTxCaQImtYuePYTyS1GES7LAjKB00QCgvjTYiLhpxj4&usqp=CAU',
      email: 'jacob.neal@example.com',
    },
    {
      id: 'drskm',
      name: 'درسا كامياران',
      age: 27,
      image: 'https://pbs.twimg.com/media/E7Yd809XIAY7lLI.jpg',
      email: 'drs.kmyrn@example.com',
    },
    {
      id: 'zhoze',
      name: 'Pranav Raj',
      age: 54,
      image: 'https://cciedump.spoto.net/static/upload/images/avatar/%E5%B7%B2%E7%94%A864.jpg',
      email: 'pranav.raj@cc.ieh@example.com',
    },
    {
      id: '3793794T',
      name: 'Victoria Butler',
      age: 62,
      image: 'https://randomuser.me/api/portraits/women/17.jpg',
      email: 'victoria.butler@example.com',
    },
    {
      id: '9143077T',
      name: 'Rich Clark',
      age: 51,
      image: 'https://randomuser.me/api/portraits/men/42.jpg',
      email: 'rich.clark@example.com',
    },
    {
      id: 'SC 18 90 45 Z',
      name: 'Umit Ozturk',
      age: 28,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvjmJzeqdprqerotwFbdohiJxkyIOVjTT7545pEiuByJgsKfS2Nx1ItwFj3fanSxriDo0&usqp=CAU',
      email: 'umit.ozturk@example.com',
    },
  ];
  
  export default data;
  